import 'package:flutter/material.dart';

class CustomAppBar extends AppBar {
  CustomAppBar({
    super.key,
    required super.title,
    super.centerTitle = true,
    super.leading,
    super.actions,
    super.bottom,
    super.elevation = 0,
    super.backgroundColor,
    // super.brightness,
    super.iconTheme,
    // super.textTheme,
    super.primary = true,
    super.shape,
    super.shadowColor,
    super.actionsIconTheme,
    super.toolbarOpacity = 1,
    super.bottomOpacity = 1,
    super.flexibleSpace,
    super.automaticallyImplyLeading = true,
    super.excludeHeaderSemantics = false,
    super.foregroundColor,
    super.leadingWidth,
    super.scrolledUnderElevation = 0,
    super.surfaceTintColor,
    super.titleSpacing,
    super.titleTextStyle,
    super.toolbarHeight,
    super.toolbarTextStyle ,
    super.systemOverlayStyle,
  });
}
