name: dots
description: dotsapp .

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  analyzer: ^4.6.0
  awesome_dialog: ^3.0.2
  bloc: ^8.0.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dialogs: ^3.0.0
  flutter_extension_pk:
    git:
      url: https://github.com/Astroshahawy/flutter_extension_pk.git
  flutter_form_builder: ^9.0.0
  flutter_hooks: ^0.18.4
  flutter_local_notifications: ^17.2.0
  flutter_native_splash: ^2.2.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  form_builder_validators: ^11.0.0
  formz: ^0.4.1
  geeks_service:
    git:
      url: https://github.com/Astroshahawy/geeks_service.git
  geeks_theme:
    git:
      url: https://github.com/Astroshahawy/geeks_theme.git
  geeks_widget:
    git:
      url: https://github.com/Astroshahawy/geeks_widget.git
  geocoding: ^2.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconify_flutter: ^0.0.4
  image_picker: ^0.8.7+5
  json_annotation: 4.5.0
  keyboard_dismisser: ^3.0.0
  location: ^5.0.0
  lottie: ^1.3.0
  percent_indicator: ^4.2.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.3
  webview_flutter: ^4.0.2

dev_dependencies:
  build_runner: 2.1.11
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/
    - assets/svg/
    - assets/images/on_boarding/
    - assets/l10n/ar.json
    - assets/l10n/en.json

  fonts:
    - family: Shamel
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_FFShamelFamily-SansOneBook-1.ttf
# flutter_native_splash-development.yaml
flutter_native_splash:
  image: assets/images/final.png
  background_image: assets/images/splash.png
  # color: "#F9F2ED"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png
