// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvfxi2yu5dm_Jta3koL118B1fT6cuBTk',
    appId: '1:908444854787:web:7a445a748321969dc27c36',
    messagingSenderId: '908444854787',
    projectId: 'dots-vendor',
    authDomain: 'dots-vendor.firebaseapp.com',
    storageBucket: 'dots-vendor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz3r2xdgYCv7whANW6uTqxsO-PNhHA0P4',
    appId: '1:908444854787:android:2c99d1bf381bcf35c27c36',
    messagingSenderId: '908444854787',
    projectId: 'dots-vendor',
    storageBucket: 'dots-vendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6qaP-pc_uLfWEBaZq1mhxbcHl-soeSoQ',
    appId: '1:908444854787:ios:e0bcf830f01dead9c27c36',
    messagingSenderId: '908444854787',
    projectId: 'dots-vendor',
    storageBucket: 'dots-vendor.appspot.com',
    iosClientId: '908444854787-98e9f1s39tg1nq7tkura1hqnucitot28.apps.googleusercontent.com',
    iosBundleId: 'com.dots.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6qaP-pc_uLfWEBaZq1mhxbcHl-soeSoQ',
    appId: '1:908444854787:ios:e0bcf830f01dead9c27c36',
    messagingSenderId: '908444854787',
    projectId: 'dots-vendor',
    storageBucket: 'dots-vendor.appspot.com',
    iosClientId: '908444854787-98e9f1s39tg1nq7tkura1hqnucitot28.apps.googleusercontent.com',
    iosBundleId: 'com.dots.store',
  );
}
